source/source/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.views.generic import RedirectView
from webapp.views import (
    IndexView,
    CreateTaskView,
    TaskView,
    TaskUpdateView,
    TaskDeleteView,
    CreateProjectView,
    ProjectView,
    ProjectUpdateView,
    ProjectDeleteView,
    IndexView_,
    ProjectCreateTask,
    ChangeProjectUsers,
    ProjectUsers,
)

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name="main_page"),
    path('tasks/', RedirectView.as_view(pattern_name="main_page")),
    path('task/create_task/', CreateTaskView.as_view(), name="task_add"),
    path('task_view/<int:pk>/', TaskView.as_view(template_name="task_view.html"), name="task_view"),
    path('task_view/<int:pk>/update/', TaskUpdateView.as_view(), name="task_update"),
    path('task_view/<int:pk>/delete/', TaskDeleteView.as_view(), name="task_delete"),
    path('project/create_project/', CreateProjectView.as_view(), name="project_add"),
    path('project_view/<int:pk>/', ProjectView.as_view(template_name="projects/view.html"), name="project_view"),
    path('project_view/<int:pk>/update/', ProjectUpdateView.as_view(), name="project_update"),
    path('project_view/<int:pk>/delete/', ProjectDeleteView.as_view(), name="project_delete"),
    path('projects/', IndexView_.as_view(), name="main_page2"),
    path('project/<int:pk>/task/add/', ProjectCreateTask.as_view(), name="project_task_add"),
    path('project/<int:pk>/change_users/', ChangeProjectUsers.as_view(), name='change_project_users'),
    path('project/<int:project_pk>/users/', ProjectUsers.as_view(),  name='project_users'),
]

source/webapp/models.py
from django.db import models

# Create your models here.
from webapp.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.urls import reverse


class Task(models.Model):
    description = models.CharField(max_length=200, null=False, blank=False, verbose_name="Description",
                                   validators=(MinLengthValidator(20),))
    detailed_description = models.TextField(max_length=2000, null=True, blank=True, verbose_name="Detailed_description",
                                            validators=(MinLengthValidator(15),))
    statuses = models.ForeignKey('webapp.StatusModel', default='new', on_delete=models.PROTECT,
                                 related_name='status', verbose_name="Status")
    project = models.ForeignKey('webapp.Project', default=None, on_delete=models.PROTECT,
                                related_name='tasks', verbose_name="Project")
    types = models.ManyToManyField('webapp.TypeModel', max_length=15,  related_name='types')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date created")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Date changed")

    def get_absolute_url(self):
        return reverse('webapp:task_view', kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.pk}. {self.description}."

    class Meta:
        db_table = 'Tasks'
        verbose_name = 'task'
        verbose_name_plural = 'tasks'
        permissions = (
            ("add_task_in_own_project", "Add tasks in own project"),
            ("change_task_in_own_project", "Change tasks in own project"),
            ("delete_task_in_own_project", "Delete tasks in own project"),
        )


class StatusModel(models.Model):
    title = models.CharField(max_length=15, null=False, blank=False)

    def __str__(self):
        return f"{self.pk} - {self.title}"

    class Meta:
        db_table = 'Statuses'
        verbose_name = 'status'
        verbose_name_plural = 'statuses'


class TypeModel(models.Model):
    title = models.CharField(max_length=15, null=False, blank=False)

    def __str__(self):
        return f"{self.pk} - {self.title}"

    class Meta:
        db_table = 'Types'
        verbose_name = 'type'
        verbose_name_plural = 'types'


class Project(models.Model):
    date_started = models.DateField(verbose_name="Date started", null=False, blank=False)
    date_finished = models.DateField(verbose_name="Date finished", null=True, blank=True)
    title = models.CharField(max_length=20, null=False, blank=False, verbose_name="Title",
                             validators=(MinLengthValidator(7),))
    description = models.TextField(max_length=200, null=False, blank=False, verbose_name="Description",
                                   validators=(MinLengthValidator(15),))
    users = models.ManyToManyField(User, related_name='projects', verbose_name="Users of project")

    def get_absolute_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.pk}:{self.title}."

    class Meta:
        db_table = 'Projects'
        verbose_name = 'project'
        verbose_name_plural = 'projects'
        permissions = (
            ("change_user_in_own_project", "Change user in own project"),
        )

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets
from webapp.models import Task, TypeModel, StatusModel, Project


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = []
        widgets = {
            'detailed_description': forms.Textarea(attrs={'rows': 5, 'cols': 50}),
            'types': forms.CheckboxSelectMultiple,
        }

    def clean_description(self):
        if len(self.cleaned_data.get('description')) < 20:
            raise ValidationError(f"The description field must be more than 20 symbols!")
        return self.cleaned_data.get('description')

    def clean_detailed_description(self):
        if len(self.cleaned_data.get('detailed_description')) > 2000:
            raise ValidationError(f"The detailed description field must be less than 2000 symbols!")
        return self.cleaned_data.get('detailed_description')


class SearchForm(forms.Form):
    search = forms.CharField(max_length=30, required=False, label="Search")


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude = []
        widgets = {
            'date_started': forms.SelectDateWidget(),
            'date_finished': forms.SelectDateWidget(),
            'user': forms.CheckboxSelectMultiple,
        }


class TaskDeleteForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("description",)

    def clean_title(self):
        print(self.instance.title, self.cleaned_data.get("description"))
        if self.instance.title != self.cleaned_data.get("description"):
            print('error')
            raise ValidationError("Description isn't valid")
        return self.cleaned_data.get("description")


class ProjectDeleteForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ("title",)

    def clean_title(self):
        print(self.instance.title, self.cleaned_data.get("title"))
        if self.instance.title != self.cleaned_data.get("title"):
            print('error')
            raise ValidationError("Title isn't valid")
        return self.cleaned_data.get("title")


class ProjectUsersForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('users',)

source/webapp/views/base.py
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import TemplateView


class ListView(TemplateView):
    model = None
    context_key = "objects"


    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context[self.context_key] = self.model.objects.all()
        return context

class FormView(View):
    form_class = None
    template_name = None
    redirect_url = ""
    object = None

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = self.get_context_data(form=form)
        print(context)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    def form_valid(self, form):
        return self.get_redirect_url()

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context)

    def get_redirect_url(self):
        return redirect(self.redirect_url)

    def get_context_data(self, **kwargs):
        return kwargs

source/webapp/views/projects.py
from django.contrib.auth.mixins import (
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.views.base import TemplateView
from webapp.forms import ProjectForm, TaskForm, ProjectDeleteForm, ProjectUsersForm
from webapp.models import Project, Task


class IndexView_(ListView):
    model = Project
    context_object_name = "projects"
    template_name = "projects/index2.html"
    paginate_by = 3
    paginate_orphans = 0

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by("-date_started")


class CreateProjectView(PermissionRequiredMixin, CreateView):
    permission_required = "webapp.add_project"
    model = Project
    form_class = ProjectForm
    template_name = "projects/create.html"

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        response = super(CreateProjectView, self).form_valid(form)
        self.object.users.add(self.request.user)
        return response


class ProjectView(DetailView):
    template_name = 'projects/view.html'
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ProjectUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = "webapp.change_project"
    form_class = ProjectForm
    template_name = "projects/update.html"
    model = Project

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})


class ProjectDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "webapp.delete_project"
    model = Project
    template_name = "projects/delete.html"
    success_url = reverse_lazy('webapp:main_page2')

    # def dispatch(self, request, *args, **kwargs):
    #     if self.request.method == "POST":
    #         self.object_form = ProjectDeleteForm(instance=self.get_object(), data=self.request.POST)
    #     else:
    #         self.object_form = ProjectDeleteForm()
    #     return super().dispatch(request, *args, **kwargs)
    #
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['form'] = self.object_form
    #     return context
    #
    # def post(self, request, *args, **kwargs):
    #     if self.object_form.is_valid():
    #         return super().delete(request, *args, **kwargs)
    #     return super().get(request, *args, **kwargs)


class ProjectCreateTask(PermissionRequiredMixin, CreateView):
    permission_required = "webapp.add_task_in_own_project"
    model = Task
    template_name = 'projects/create_task.html'
    form_class = TaskForm

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        task = form.save(commit=False)
        task.project = project
        project.save()
        return redirect('webapp:task_view', pk=task.pk)

    def has_permission(self):
        return super().has_permission() or self.request.user.username == self.get_object().user_pr


class ChangeProjectUsers(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'projects/change_users.html'
    form_class = ProjectUsersForm
    permission_required = 'webapp.change_user_in_own_project'

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})

    def has_permission(self):
        return (
                super().has_permission()
                and self.get_object().users.filter(pk=self.request.user.pk).exists()
        )


class ProjectUsers(DetailView):
    model = Project
    template_name = 'projects/project_users.html'
    pk_url_kwarg = 'project_pk'

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})

source/webapp/views/tasks.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.views.base import TemplateView, FormView as CustomFormView
from webapp.forms import TaskForm, SearchForm, TaskDeleteForm
from webapp.models import Task, Project

class IndexView(ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "index.html"
    paginate_by = 10
    paginate_orphans = 0

    def get(self, request, *args, **kwargs):
        self.form = self.get_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)


    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            print(self.search_value)
            query = Q(description__icontains=self.search_value) | Q(detailed_description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset.order_by("-updated_at")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = SearchForm()
        if self.search_value:
            context['form'] = SearchForm(initial={"search": self.search_value})
            context['search'] = self.search_value
        return context

    def get_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get("search")


class CreateTaskView(PermissionRequiredMixin, CreateView):
    permission_required = "webapp.add_task"
    model = Task
    form_class = TaskForm
    template_name = "task_create.html"

    def get_project(self):
        project_pk = self.request.POST.get("project")
        return get_object_or_404(Project, pk=project_pk)

    def has_permission(self):
        has_permission = super().has_permission()

        if self.request.method == "POST":
            has_permission = (
                has_permission
                and self.get_project().users.filter(pk=self.request.user.pk).exists()
            )
        return has_permission

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def get_redirect_url(self):
        return redirect('webapp:task_view', pk=self.object.pk)


class TaskView(DetailView):
    template_name = 'tasks/task_view.html'
    model = Task

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        types = self.object.types.order_by("title")
        context['types'] = types
        return context


class TaskUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = "webapp.change_task_in_own_project"
    form_class = TaskForm
    template_name = "task_update.html"
    model = Task

    def get_success_url(self):
        return reverse('webapp:task_view', kwargs={'pk': self.object.pk})

    def has_permission(self):
        return (
            super().has_permission()
            and self.get_object().project.users.filter(pk=self.request.user.pk).exists()
        )


class TaskDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "webapp.delete_task_in_own_project"
    model = Task
    template_name = "task_delete.html"
    success_url = reverse_lazy('webapp:main_page')

    def has_permission(self):
        return (
                super().has_permission()
                and self.get_object().project.users.filter(pk=self.request.user.pk).exists()
        )

source/webapp/templates/projects/all_projects_view.html
{% extends 'base.html' %}

{% block nav %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'webapp:main_page' %}">All tasks</a>
</li>
{% endblock %}

source/webapp/templates/projects/change_users.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Project {{ project.pk }}
{% endblock %}

{% block nav %}{% endblock %}
{% block content %}
<h2>Change project users</h2>
</br>
<div>
        <form method="post">
            {% include 'partial/form.html' with button_text="Save" %}
        </form>
</div>

{% endblock %}

source/webapp/templates/projects/create.html
{% extends 'base.html' %}

{% block title %}Project create page{% endblock %}
{% block nav %}{% endblock %}
{% block content %}
<h1>Create Project</h1>

<form method="post">
    {% include "partial/form.html" with button_text="Create" %}
</form>
{% endblock %}

source/webapp/templates/projects/create_task.html
{% extends 'base.html' %}

{% block title %}Task Create{% endblock %}

{% block content %}
    <h1>Task Create</h1>
    <form action="" method="post">
        {% include 'partial/form.html' with button_text='Create' %}
    </form>
{% endblock %}

source/webapp/templates/projects/delete.html
{% extends "base.html" %}

{% block content %}
</br>
    <form method="POST">
    {% csrf_token %}
        <h2>Enter the project's title {{ project.title }}</h2>
        </br>
        {% include 'partial/form.html' with button_text="Delete" %}
    </form>
</br>
    <form method="GET" action="{% url 'webapp:project_view' project.pk %}" target="_blank">
   <button>No</button>
{% endblock %}

source/webapp/templates/projects/index2.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Projects page{% endblock %}
{% block content %}
<h1>📝PROJECTS📝</h1>
</br>
</br>
    {% for project in projects %}
        <h3>{{ project.title }}</h3>
        {% if not user.is_authenticated %}
            <a href='{{ project.get_absolute_url }}'>Show the project🔓</a>
        {% else %}
        <p>
            <a href='{{ project.get_absolute_url }}'>Show the project🔓</a>
            {% if perms.webapp.change_project %}
                <a href='{% url "webapp:project_update" project.pk%}'>Edit the project📝</a>
            {% endif %}
            {% if perms.webapp.delete_project %}
                <a href='{% url "webapp:project_delete" project.pk%}'>Delete the project✂️</a>
            {% endif %}
        </p>
        {% endif %}
    {% endfor %}

{% endblock %}

source/webapp/templates/projects/project_users.html
{% extends 'base.html' %}

{% block content %}

    {% for user in project.users.all %}
        <p>
            <a href="{% url 'accounts:profile' user.id %}">{{ user }}</a>
        </p>
    {% endfor %}
    {% if perms.webapp.can_manage_users %}
    <a href="{% url 'webapp:change_project_users' project.pk %}"><button>Add user</button></a>
    {% endif %}
{% endblock %}

source/webapp/templates/projects/update.html
{% extends 'base.html' %}

{% block title %}Project Update{% endblock %}

{% block content %}
    <h1>Edit the project</h1>
    <form action="" method="post">
        {% include 'partial/form.html' with button_text='Edit' %}
    </form>
{% endblock %}

source/webapp/templates/projects/view.html
{% extends 'base.html' %}
{% block title %}Project {{project.pk}}{% endblock %}
{% block nav %}
    {% if not user.is_authenticated %}
{{pass}}
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:project_task_add' project.pk %}">Add Task</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:project_update' project.pk %}">Edit project</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:project_delete' project.pk %}">Delete project</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:change_project_users' project.pk %}">Change users of this project</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:project_users' project.pk %}">Users of this project</a>
        </li>
{% endif %}
{% endblock %}
{% block content %}
    <h1>{{ project.title }}</h1>
    <h2>{{ project.description }}</h2>
    <p>{{ project.date_started }}</p>
    <p>{{ project.date_finished }}</p>
<h3>Tasks</h3>

    {% for task in project.tasks.all %}
        <span>{{ forloop.counter }}</span>
        <h3>{{ task.description }}</h3>
        {% if not user.is_authenticated %}
            <a href='{{ task.get_absolute_url }}'>Show the task🔓</a>
        {% else %}
        <p>
            <a href='{{ task.get_absolute_url }}'>Show the task🔓</a>
            {% if perms.webapp.change_task %}
                <a href='{% url "webapp:task_update" task.pk %}'>Edit the task📝</a>
            {% endif %}
            {% if perms.webapp.delete_task %}
                <a href='{% url "webapp:task_delete" task.pk %}'>Delete the task✂️</a>
            {% endif %}
        </p>
        {% endif %}
    {% endfor %}

<h3>Users</h3>
    {% for user_pr in project.users.all %}
    <h5 style="color: whitesmoke">{{ user_pr.username }}</h5>
    {% empty %}
        <li>There are no users in the project yet</li>
    {% endfor %}

    {% if is_paginated %}
            {% include 'partial/pagination.html' %}
    {% endif %}

{% endblock %}